/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glosario;

import java.awt.*;
import javax.swing.*;
import javax.swing.filechooser.*;
import java.io.*;
import javax.imageio.ImageIO;


public class JFrameGlosario extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public JFrameGlosario() {
        initComponents();
        try {
        this.setIconImage(ImageIO.read(new File("book.png")));
        } catch (Exception ex) {
            System.err.println("No se pudo cargar el icono del JFrame");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLTema = new javax.swing.JLabel();
        jLabelTema = new javax.swing.JLabel();
        jLabelLCantidadTerminos = new javax.swing.JLabel();
        jLabelCantidadTerminos = new javax.swing.JLabel();
        jTextFieldBusqueda = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDefinicion = new javax.swing.JTextArea();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFichero = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jMenuItemCargar = new javax.swing.JMenuItem();
        jMenuDatos = new javax.swing.JMenu();
        jMenuItemCambiarTema = new javax.swing.JMenuItem();
        jMenuItemAnandir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glosario - Ejercicio de ficheros");
        setResizable(false);

        jLabelLTema.setText("Tema:");

        jLabelTema.setText("-");

        jLabelLCantidadTerminos.setText("Cantidad de términos:");

        jLabelCantidadTerminos.setText("-");

        jTextFieldBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBusquedaActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");

        jTextAreaDefinicion.setEditable(false);
        jTextAreaDefinicion.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jTextAreaDefinicion.setColumns(20);
        jTextAreaDefinicion.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jTextAreaDefinicion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDefinicion);

        jMenuFichero.setText("Fichero");

        jMenuItemNuevo.setText("Nuevo");
        jMenuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoActionPerformed(evt);
            }
        });
        jMenuFichero.add(jMenuItemNuevo);
        jMenuFichero.add(jSeparator1);

        jMenuItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/download.png"))); // NOI18N
        jMenuItemGuardar.setText("Guardar...");
        jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarActionPerformed(evt);
            }
        });
        jMenuFichero.add(jMenuItemGuardar);

        jMenuItemCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/upload.png"))); // NOI18N
        jMenuItemCargar.setText("Cargar...");
        jMenuItemCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargarActionPerformed(evt);
            }
        });
        jMenuFichero.add(jMenuItemCargar);

        jMenuBar.add(jMenuFichero);

        jMenuDatos.setText("Datos");

        jMenuItemCambiarTema.setText("Cabiar tema...");
        jMenuItemCambiarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiarTemaActionPerformed(evt);
            }
        });
        jMenuDatos.add(jMenuItemCambiarTema);

        jMenuItemAnandir.setText("Añadir...");
        jMenuItemAnandir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnandirActionPerformed(evt);
            }
        });
        jMenuDatos.add(jMenuItemAnandir);

        jMenuBar.add(jMenuDatos);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLCantidadTerminos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCantidadTerminos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLTema)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTema, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 197, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLTema)
                    .addComponent(jLabelTema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLCantidadTerminos)
                    .addComponent(jLabelCantidadTerminos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaActionPerformed

    }//GEN-LAST:event_jTextFieldBusquedaActionPerformed

    private void jMenuItemCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargarActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Formato nosequé (.nsq)", "jpg", "gif");
        chooser.addChoosableFileFilter(filter);
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Formato nosecuantos (.nsc)", "glosario"));
        JTextArea message = new JTextArea();
        message.setText("La extensión determina el formato.\n Escriba con responsabilidad");
        message.setEditable(false);
        chooser.setAccessory(message);
        int returnVal = chooser.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: "
                    + chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jMenuItemCargarActionPerformed

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        JOptionPane.showMessageDialog(this, "Guardar");
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void jMenuItemAnandirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnandirActionPerformed
        JDialogTermino dialogo = new JDialogTermino(this, true);
        dialogo.setVisible(true);
        if (dialogo.getGuardarPulsado()) {
            String termino = dialogo.getTermino();
            System.out.println("Termino: " + termino);
        }

    }//GEN-LAST:event_jMenuItemAnandirActionPerformed

    private void jMenuItemCambiarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCambiarTemaActionPerformed
        String tema = JOptionPane.showInputDialog(this, "Introduce tema:");
        System.out.println("Tema: " + tema);
    }//GEN-LAST:event_jMenuItemCambiarTemaActionPerformed

    private void jMenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoActionPerformed
        JOptionPane.showConfirmDialog(this, "Se van a borrar todos los datos. Confirme la operación, por favor");
    }//GEN-LAST:event_jMenuItemNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGlosario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGlosario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGlosario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGlosario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGlosario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabelCantidadTerminos;
    private javax.swing.JLabel jLabelLCantidadTerminos;
    private javax.swing.JLabel jLabelLTema;
    private javax.swing.JLabel jLabelTema;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuDatos;
    private javax.swing.JMenu jMenuFichero;
    private javax.swing.JMenuItem jMenuItemAnandir;
    private javax.swing.JMenuItem jMenuItemCambiarTema;
    private javax.swing.JMenuItem jMenuItemCargar;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextAreaDefinicion;
    private javax.swing.JTextField jTextFieldBusqueda;
    // End of variables declaration//GEN-END:variables
}
