/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.*;
import javax.swing.*;
import javax.swing.filechooser.*;
import java.io.*;
import javax.imageio.ImageIO;
import modelo.Glosario;
import ficheros.*;

public class JFrameGlosario extends javax.swing.JFrame {

    Glosario glosario;

    /**
     * Creates new form NewJFrame
     */
    public JFrameGlosario() {
        initComponents();
        try {
            this.setIconImage(ImageIO.read(new File("book.png")));
        } catch (Exception ex) {
            System.err.println("No se pudo cargar el icono del JFrame");
        }
        glosario = new Glosario();
        actualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLTema = new javax.swing.JLabel();
        jLabelTema = new javax.swing.JLabel();
        jLabelLCantidadTerminos = new javax.swing.JLabel();
        jLabelCantidadTerminos = new javax.swing.JLabel();
        jTextFieldBusqueda = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDefinicion = new javax.swing.JTextArea();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFichero = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jMenuItemCargar = new javax.swing.JMenuItem();
        jMenuDatos = new javax.swing.JMenu();
        jMenuItemCambiarTema = new javax.swing.JMenuItem();
        jMenuItemAnandir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glosario - Ejercicio de ficheros");
        setResizable(false);

        jLabelLTema.setText("Tema:");

        jLabelTema.setText("-");

        jLabelLCantidadTerminos.setText("Cantidad de términos:");

        jLabelCantidadTerminos.setText("-");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTextAreaDefinicion.setEditable(false);
        jTextAreaDefinicion.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jTextAreaDefinicion.setColumns(20);
        jTextAreaDefinicion.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jTextAreaDefinicion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDefinicion);

        jMenuFichero.setText("Fichero");

        jMenuItemNuevo.setText("Nuevo");
        jMenuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoActionPerformed(evt);
            }
        });
        jMenuFichero.add(jMenuItemNuevo);
        jMenuFichero.add(jSeparator1);

        jMenuItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/download.png"))); // NOI18N
        jMenuItemGuardar.setText("Guardar...");
        jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarActionPerformed(evt);
            }
        });
        jMenuFichero.add(jMenuItemGuardar);

        jMenuItemCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/upload.png"))); // NOI18N
        jMenuItemCargar.setText("Cargar...");
        jMenuItemCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargarActionPerformed(evt);
            }
        });
        jMenuFichero.add(jMenuItemCargar);

        jMenuBar.add(jMenuFichero);

        jMenuDatos.setText("Datos");

        jMenuItemCambiarTema.setText("Cabiar tema...");
        jMenuItemCambiarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiarTemaActionPerformed(evt);
            }
        });
        jMenuDatos.add(jMenuItemCambiarTema);

        jMenuItemAnandir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAnandir.setText("Añadir...");
        jMenuItemAnandir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnandirActionPerformed(evt);
            }
        });
        jMenuDatos.add(jMenuItemAnandir);

        jMenuBar.add(jMenuDatos);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLCantidadTerminos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCantidadTerminos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLTema)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTema, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 197, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLTema)
                    .addComponent(jLabelTema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLCantidadTerminos)
                    .addComponent(jLabelCantidadTerminos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizar() {
        jLabelTema.setText(glosario.getTema());
        jLabelCantidadTerminos.setText(String.valueOf(glosario.getCantidad()));
    }

    private void jMenuItemCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargarActionPerformed
        JFileChooser chooser = new JFileChooser();
        // añadimos las extensiones aceptadas
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Texto CSV (*.gltxt)", "gltxt"));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Binario (*.glbin)", "glbin"));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Serializado nativo (*.globj)", "globj"));

        // añadir un mensaje al JFileChooser
        JTextArea message = new JTextArea();
        message.setText("La extensión determina el formato.");
        message.setEditable(false);
        chooser.setAccessory(message);
        // Mostrar
        int returnVal = chooser.showOpenDialog(this);

        // Si no se da al boton de aceptar, no hay nada más que hacer
        if (returnVal != JFileChooser.APPROVE_OPTION) {
            return;
        }

        // Obtener el nombre del fichero, Cambiar la estrategia de carga en base a él y cargar
        String filename = null;
        ICargar estrategia = null;

        // Obtener nombre de fichero y extensión.
        // ******** REVISAR ***********
        filename = chooser.getSelectedFile().getAbsolutePath();
        String extension = filename.substring(filename.lastIndexOf('.') + 1).toLowerCase();
        // Cambiar estrategia
        switch (extension) {
            case "gltxt":
                estrategia = new CargaCsv();
                break;
            case "glbin":
                // TODO
                break;
            case "globj":
                // TODO
                break;
            default:
                // No hay nada que hacer.
                JOptionPane.showMessageDialog(this, "No se pudo reconocer el formato del fichero");
                return;
        }

        boolean todoOk = true;
        try {
            glosario = estrategia.cargar(filename);
        } catch (IOException ex) {
            todoOk = false;
            ex.printStackTrace();
        }

        if (todoOk) {
            JOptionPane.showMessageDialog(this, "Fichero cargado con éxito.");
            actualizar();
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: No se pudo cargar el fichero.");
        }

    }//GEN-LAST:event_jMenuItemCargarActionPerformed

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        JOptionPane.showMessageDialog(this, "Guardar no implementado");
        // TODO Implementar esto
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void jMenuItemAnandirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnandirActionPerformed
        JDialogTermino dialogo = new JDialogTermino(this, true);
        dialogo.setVisible(true);

        if (dialogo.getGuardarPulsado()) {
            String termino = dialogo.getTermino();
            String definicion = dialogo.getDefinicion();
            glosario.annadir(termino, definicion);
            actualizar();
        }
    }//GEN-LAST:event_jMenuItemAnandirActionPerformed

    private void jMenuItemCambiarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCambiarTemaActionPerformed
        String tema = JOptionPane.showInputDialog(this, "Introduce tema:");
        glosario.setTema(tema);
        actualizar();
    }//GEN-LAST:event_jMenuItemCambiarTemaActionPerformed

    private void jMenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Se van a borrar todos los datos. Confirme la operación, por favor");
        if (response == JOptionPane.YES_OPTION) {
            glosario.vaciar();
            actualizar();
        } else {
            JOptionPane.showMessageDialog(this, "Operación cancelada");
        }
    }//GEN-LAST:event_jMenuItemNuevoActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String termino = jTextFieldBusqueda.getText();
        String definicion = glosario.buscar(termino);

        if (definicion == null) {
            definicion = "[No encontrado]";

        }
        jTextAreaDefinicion.setText(definicion);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager
                            .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info
                        .getName())) {
                    javax.swing.UIManager
                            .setLookAndFeel(info
                                    .getClassName());

                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger
                    .getLogger(JFrameGlosario.class
                            .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger
                    .getLogger(JFrameGlosario.class
                            .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger
                    .getLogger(JFrameGlosario.class
                            .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger
                    .getLogger(JFrameGlosario.class
                            .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue
                .invokeLater(new Runnable() {
                    public void run() {
                        new JFrameGlosario().setVisible(true);

                    }
                });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabelCantidadTerminos;
    private javax.swing.JLabel jLabelLCantidadTerminos;
    private javax.swing.JLabel jLabelLTema;
    private javax.swing.JLabel jLabelTema;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuDatos;
    private javax.swing.JMenu jMenuFichero;
    private javax.swing.JMenuItem jMenuItemAnandir;
    private javax.swing.JMenuItem jMenuItemCambiarTema;
    private javax.swing.JMenuItem jMenuItemCargar;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextAreaDefinicion;
    private javax.swing.JTextField jTextFieldBusqueda;
    // End of variables declaration//GEN-END:variables
}
